[tool.poetry]
name = "prefect-yaml"
version = "2022.1.0"
description = "Prefect scheduler for YAML configuration"
authors = ["Factor Pricing Model <factor.pricing.model@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/factorpricingmodel/prefect-yaml"
documentation = "https://prefect-yaml.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
]
packages = [
    { include = "prefect_yaml", from = "src" },
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/factorpricingmodel/prefect-yaml/issues"
"Changelog" = "https://github.com/factorpricingmodel/prefect-yaml/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

# Documentation Dependencies
Sphinx = {version = "^5.0", optional = true}
insipid-sphinx-theme = {version = "^0.3.6", optional = true}
myst-parser = {version = "^0.18", optional = true}
ruamel-yaml = "^0.17.21"
prefect = "^2.7.1"
click = "^8.1.3"

[tool.poetry.extras]
docs = [
    "myst-parser",
    "sphinx",
    "insipid-sphinx-theme",
]

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-cov = "^3.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
docformatter = "^1.5.0"

[tool.semantic_release]
branch = "main"
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "src/prefect_yaml/__init__.py:__version__"
build_command = "pip install poetry && poetry build"

[tool.pytest.ini_options]
addopts = "-v -Wdefault --cov=prefect_yaml --cov-report=term-missing:skip-covered"
pythonpath = ["src"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@overload",
    "if TYPE_CHECKING",
    "raise NotImplementedError",
]

[tool.isort]
profile = "black"
known_first_party = ["prefect_yaml", "tests"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "src/"
no_implicit_optional = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true
exclude = [
    'docs/.*',
    'setup.py',
]

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true

[[tool.mypy.overrides]]
module = "docs.*"
ignore_errors = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
prefect-yaml = 'prefect_yaml.cli:main'
